/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fakeArduino_JNIArduino */

#ifndef _Included_fakeArduino_JNIArduino
#define _Included_fakeArduino_JNIArduino
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fakeArduino_JNIArduino
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fakeArduino_JNIArduino_init
  (JNIEnv *, jobject);

/*
 * Class:     fakeArduino_JNIArduino
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fakeArduino_JNIArduino_close
  (JNIEnv *, jobject);

/*
 * Class:     fakeArduino_JNIArduino
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fakeArduino_JNIArduino_setup
  (JNIEnv *, jobject);

/*
 * Class:     fakeArduino_JNIArduino
 * Method:    loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fakeArduino_JNIArduino_loop
  (JNIEnv *, jobject);

/*
 * Class:     fakeArduino_JNIArduino
 * Method:    getRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fakeArduino_JNIArduino_getRunning
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
